### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by KnSun99** [TorchDR/TorchDR#116]
RTX3090 (24G);  memory bank: 64G

Hi,
    I want to perform umap dimensionality reduction on a 140,000 *20000 matrix. But, CUDA out of memory.
    So I was wondering if there was a solution?
    Can it run in batches.

    Also, can the module save the model? Convenient for the next import run.

Thank you.

**Comment by huguesva** [comment]
Hello @KnSun99,

thanks for the issue! 
try setting `keops=True` when initializing the UMAP model, this will solve your problem. 
We will change the default behavior for the release.  

Also, what do you mean precisely by "save the model" ? do you mean a parametric version that you can run on new data samples?

**Comment by KnSun99** [comment]
Thank you for the response!

In addition, setting keops=True seems to require a Linux environment, and an error is reported in the Win11 environment.



For "save the model", I have the first matrix for umap dimensionality reduction, now I have the second matrix and want to implement the mapping of the second matrix with the umap model generated by the first matrix.

"save the model":    Similar to saving templates in umap for MATLAB.

**Comment by huguesva** [comment]
Did you try having a look at the keops documentation ? https://www.kernel-operations.io/keops/python/installation.html

For the model saving, if I'm correct you refer to the transform function in UMAP right? Note that these neighbor embedding methods are not primarily design to work with a transform method, but it seems that UMAP has a workaround for this. 
I opened an issue : #123 , we will take a look and consider implementing this in the future. Thanks a lot for the suggestion ! If you have some insights on how to implement this I am happy to discuss.

**Comment by KnSun99** [comment]
Look at the keops documentation   https://www.kernel-operations.io/keops/python/installation.html

It can be installed normally on Linux.

However, in Windows 11, an error will be reported.
![image](https://github.com/user-attachments/assets/0b21078c-e4a5-4646-b944-66c3d6c71d75)
