### ISSUE TITLE
DOC "increasing function" in `false_position` and `binary_search`

### ISSUE THREAD

**Issue by mathurinm** [TorchDR/TorchDR#4]
The docstrings of these two functions mentions "increasing functions" which is not clear for a function from Rn to Rn ; their behavior is also tested on $(x - 1)^2$ which is not increasing

**Comment by huguesva** [comment]
Hello @mathurinm,

Thanks for the remark, it is a batched version of a 1D function that takes as input x > 0 .
Will be made clearer in the next push.

**Comment by mathurinm** [comment]
Ok thanks, two remarks:
- if $x$ is assumed to be positive testing with the constraint -0.5 < x < 2 in the test may be misleading 
- If you want to strengthen the tests you should test a case where the boundaries are active ie min x over [-1, 1]

**Comment by huguesva** [comment]
we modified the test and docstring to take into account your advice, thanks!

**Comment by huguesva** [comment]
Following your advice we modified the test and docstring, thanks!
